service:
  name: get-amz-listing-report

package:
  individually: true
  exclude:
    - '**/**'

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags: 
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: mws-subscriptions
    type: sqs

layers:
  GetAmzListingReportLayer:
    path: layer
    name: ${self:service.name}-layer
    description: Layer for ${self:service.name}
    compatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
    licenseInfo: MIT
    package:
      include:
        - '**/**'

functions:
  GetAmzListingReport:
    handler: get-amz-listing-report.handler
    name: ${self:service.name}
    timeout: 900
    layers:
      - { Ref: GetAmzListingReportLayerLambdaLayer}
    package:
      include:
        - 'get-amz-listing-report.js'
        - 'helpers/**'
    environment:
      ACCESS_KEY: ${env:ACCESS_KEY}
      SELLER_ID: ${env:SELLER_ID}
      MWS_AUTH_TOKEN: ${env:MWS_AUTH_TOKEN}
    events:
      - sns:
          arn: arn:aws:sns:eu-central-1:374163881813:mws-report-topic
          topicName: mws-report-topic
          filterPolicy:
            reportType:
              - '_GET_MERCHANT_LISTINGS_ALL_DATA_'
    destinations:
      onSuccess: arn:aws:lambda:eu-central-1:374163881813:function:set-amz-stocks
