service:
  name: get-amz-report

package:
  individually: true
  exclude:
    - '**/**'

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags: 
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: mws-subscriptions
    type: sqs
  # should add a policy to allow invocation of set-stocks

layers:
  GetAmzReportLayer:
    path: layer
    name: ${self:service.name}-layer
    description: Layer for ${self:service.name}
    compatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
    licenseInfo: MIT
    package:
      include:
        - '**/**'

functions:
  GetAmzReport:
    handler: get-amz-report.handler
    name: ${self:service.name}
    layers:
      - { Ref: GetAmzReportLayerLambdaLayer}
    package:
      include:
        - 'get-amz-report.js'
        - 'helpers/**'
    environment:
      ACCESS_KEY: ${env:ACCESS_KEY},
      SELLER_ID: ${env:SELLER_ID},
      MWS_AUTH_TOKEN: ${env:MWS_AUTH_TOKEN}
    events:
      - sqs:
          arn: !GetAtt MwsReportSubsQueue.Arn
    # should define set-stocks lambda as destination for this lambda

resources:
  Resources:
    MwsReportSubsQueue:
      Type: AWS::SQS::Queue
      Properties:
        QueueName: mws-report-subs-queue
    MwsReportSubsQueuePolicy:
      Type: AWS::SQS::QueuePolicy
      DependsOn:
        - MwsReportSubsQueue
      Properties: 
        Queues: 
          - !Ref MwsReportSubsQueue
        PolicyDocument:
          Version: "2012-10-17",
          Statement: 
            - Action: 
                - "SQS:GetQueueAttributes" 
                - "SQS:SendMessage"
              Effect: "Allow"
              Resource: !GetAtt MwsReportSubsQueue.Arn
              Principal:
                AWS: 
                  - "arn:aws:iam::123456789012:root"
