service:
  name: get-amz-report

package:
  individually: true
  exclude:
    - '**/**'

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags: 
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: mws-subscriptions
    type: sqs
  # should add a policy to allow invocation of set-stocks

functions:
  GetAmzReport:
    handler: get-amz-report.handler
    name: ${self:service.name}
    package:
      include:
        - 'get-amz-report.js'
        - 'helpers/**'
    events:
      - sqs:
          arn: !GetAtt MwsReportSubsQueue.Arn
    # should define set-stocks lambda as destination for this lambda

resources:
  Resources:
    MwsReportSubsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: mws-report-subs-queue
