service:
  name: get-amz-listing-report

package:
  individually: true
  exclude:
    - '**/**'

provider:
  name: aws
  runtime: nodejs12.x
  stackName: ${self:service.name}-stack
  stage: ${opt:stage, 'prod'}
  region: eu-central-1
  deploymentBucket:
    name: kaskadi-serverless-deployment-bucket
  stackTags: 
    app: kaskadi
  tags:
    app: kaskadi
    service: ${self:service.name}
    logical-unit: mws-subscriptions
    type: sqs
  # should add a policy to allow invocation of set-stocks

layers:
  GetAmzListingReportLambda:
    path: layer
    name: ${self:service.name}-layer
    description: Layer for ${self:service.name}
    compatibleRuntimes:
      - nodejs10.x
      - nodejs12.x
    licenseInfo: MIT
    package:
      include:
        - '**/**'

functions:
  GetAmzListingReport:
    handler: get-amz-listing-report.handler
    name: ${self:service.name}
    layers:
      - { Ref: GetAmzListingReportLambdaLambdaLayer}
    package:
      include:
        - 'get-amz-listing-report.js'
        - 'helpers/**'
    environment:
      ACCESS_KEY: ${env:ACCESS_KEY}
      SELLER_ID: ${env:SELLER_ID}
      MWS_AUTH_TOKEN: ${env:MWS_AUTH_TOKEN}
    events:
      - sns:
          arn: arn:aws:sns:eu-central-1:374163881813:mws-report-topic
          topicName: mws-report-topic
          filterPolicy:
            body:
              Notification:
                NotificationPayload:
                  ReportProcessingFinishedNotification:
                    ReportType:
                      - '_GET_MERCHANT_LISTINGS_ALL_DATA_'
    # should define set-stocks lambda as destination for this lambda
