# ATTENTION: no deployment should be done until serverless.yml is properly setup
name: deploy
on:
  push:
    branches:
      - 'master'
      - 'release/**'
    paths:
      - 'serverless.yml'
      - 'get-amz-listing-report.js'
      - 'helpers/**'
      - 'resources/**'
      - 'layer/**'
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: npm i
    - name: serverless check
      uses: serverless/github-action@master
      with:
        args: deploy --noDeploy
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        MWS_KEY_ID: ${{ secrets.MWS_KEY_ID }}
        MWS_KEY_SECRET: ${{ secrets.MWS_KEY_SECRET }}
        AMZ_EU_SELLER_ID: ${{ secrets.AMZ_EU_SELLER_ID }}
    - name: serverless deploy
      uses: serverless/github-action@master
      with:
        args: deploy -v
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_KEY_SECRET }}
        MWS_KEY_ID: ${{ secrets.MWS_KEY_ID }}
        MWS_KEY_SECRET: ${{ secrets.MWS_KEY_SECRET }}
        AMZ_EU_SELLER_ID: ${{ secrets.AMZ_EU_SELLER_ID }}
